version: "3.7"
services:
  app:
    container_name: gamecontext_api
    build: .
    env_file: 
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
    networks: 
    - fullstack
     
  database:
    image: postgres:13.2-alpine
    container_name: gamecontext_api_db
    env_file: 
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    networks: 
      - fullstack
    volumes:
      - data:/var/lib/postgresql/data
      # - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh    
  
  redis:
    container_name: gamecontext_api_cache
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks: 
      - fullstack

volumes:
  data:

networks:
  fullstack:
    driver: bridge
